services:
  - type: web
    name: herbal-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free

  - type: web
    name: herbal-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
